name: Github Action

on:
  push:
    branches: [master]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started Building the Project..."
      - run: echo "Running..."
