name: Github Action

on:
  push:
    branches: [master]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started Building the Project..."
      - run: echo "Running..."
  build-client-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      - run: yarn build
